# Generated by Django 3.2.12 on 2024-10-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_review'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtoms', models.TextField()),
                ('appointemt_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=100)),
                ('appointment_types', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=100)),
                ('cancel', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availaletime')),
            ],
        ),
    ]
